# SPDX-FileCopyrightText: : 2021 The PyPSA-Africa Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0.0.1

logging:
  level: INFO
  format: "%(levelname)s:%(name)s:%(message)s"

summary_dir: results
